on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: cd ./backend && ls && npm install
      - run: node app.js